-- ============================================================================
-- SQLite3 Seed Data for sse_festa_db (Extracted from Saranathan College Website)
-- Database File: sse_festa_db.sqlite
-- ============================================================================

PRAGMA foreign_keys = OFF;
DELETE FROM faculty;
DELETE FROM courses;
DELETE FROM timetables;
DELETE FROM research_centres;
DELETE FROM departments;
DELETE FROM academic_calendar;
DELETE FROM exam_notices;
DELETE FROM announcements;
DELETE FROM placement_drives;
DELETE FROM clubs;
DELETE FROM gallery;
DELETE FROM campus_buildings;
DELETE FROM contact_information;
PRAGMA foreign_keys = ON;

-- 1. Insert Departments
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('AIDS', 'Artificial Intelligence & Data Science', 'Department of Artificial Intelligence & Data Science at Saranathan College of Engineering.', 'Dr. S Ravimaran', 'hod-aids@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=aids_about');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('CE', 'Civil Engineering', 'Department of Civil Engineering at Saranathan College of Engineering.', 'Dr. A Belin Jude', 'belin-ce@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CE&tgt=civilabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('CSBS', 'Computer Science & Business System', 'Department of Computer Science & Business System at Saranathan College of Engineering.', 'Dr. S Venkatasubramanian', 'hod-csbs@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=csbs_about');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('CSE', 'Computer Science & Engineering', 'Department of Computer Science & Engineering at Saranathan College of Engineering.', 'Dr. V Punitha', 'punitha-it@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=cseabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('AIML', 'Computer Science & Engg (AI & ML)', 'Department of Computer Science & Engg (AI & ML) at Saranathan College of Engineering.', 'Dr. A Delphin Carolina Rani', 'hod-aiml@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=aimlabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('ECE', 'Electronics & Communication Engineering', 'Department of Electronics & Communication Engineering at Saranathan College of Engineering.', 'Dr. M Santhi', 'santhim@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=eceabt');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('EEE', 'Electrical & Electronics Engineering', 'Department of Electrical & Electronics Engineering at Saranathan College of Engineering.', 'Dr. C Krishnakumar', 'krishnakumar-eee@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=eeeabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('ICE', 'Instrumentation & Control Engineering', 'Department of Instrumentation & Control Engineering at Saranathan College of Engineering.', 'Dr. K Gaayathry', 'gaayathry-ice@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ICE&tgt=iceabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('IT', 'Information Technology', 'Department of Information Technology at Saranathan College of Engineering.', 'Dr. R Thillaikarasi', 'thillai-cse@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=itabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('MECH', 'Mechanical Engineering', 'Department of Mechanical Engineering at Saranathan College of Engineering.', 'N/A', 'rekha-mech@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=mechabt');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('MBA', 'Department of Management Studies', 'Department of Department of Management Studies at Saranathan College of Engineering.', 'Dr. K Karthikeyan', 'karthikeyan-mba@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MBA&tgt=mbaabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('CHE', 'Chemistry', 'Department of Chemistry at Saranathan College of Engineering.', 'Dr. L Muruganandam', 'muruganandam-che@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CHE&tgt=cheabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('ENG', 'English', 'Department of English at Saranathan College of Engineering.', 'Dr. M Bhuvaneswari', 'uma-eng@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ENG&tgt=engabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('MAT', 'Mathematics', 'Department of Mathematics at Saranathan College of Engineering.', 'Dr. G Ravichandran', 'geetha-mat@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=matabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('PHY', 'Physics', 'Department of Physics at Saranathan College of Engineering.', 'Dr. R Mariappan', 'mariappan-phy@saranathan.ac.inSaranathan', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=PHY&tgt=phyabout');
INSERT INTO departments (dept_code, dept_name, description, hod_name, email, phone, source_url) VALUES ('TAM', 'Tamil', 'Department of Tamil at Saranathan College of Engineering.', 'N/A', 'hod-tam@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=TAM&tgt=faculty');

-- 2. Insert Courses
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.E. Artificial Intelligence and Data Science', 'B.E.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 60, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.E. Civil Engineering', 'B.E.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'CE'), 60, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.Tech. Computer Science and Business System', 'B.Tech.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 60, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.E. Computer Science and Engineering', 'B.E.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 120, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.E. Computer Science & Engg (AI & ML)', 'B.E.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 60, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.E. Electronics and Communication Engineering', 'B.E.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 120, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.E. Electrical and Electronics Engineering', 'B.E.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 120, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.E. Instrumentation and Control Engineering', 'B.E.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'ICE'), 60, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.Tech. Information Technology', 'B.Tech.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 120, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('B.E. Mechanical Engineering', 'B.E.', '4 Years', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 120, 'UG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('MBA - Master of Business Administration', 'MBA', '2 Years', (SELECT dept_id FROM departments WHERE dept_code = 'MBA'), 60, 'PG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('M.E. Thermal Engineering', 'M.E.', '2 Years', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 18, 'PG', 'http://saranathan.ac.in/admission.php?tgt=courses');
INSERT INTO courses (course_name, degree, duration, dept_id, intake, programme_type, source_url) VALUES ('M.E. Power Electronics & Drives', 'M.E.', '2 Years', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 18, 'PG', 'http://saranathan.ac.in/admission.php?tgt=courses');

-- 3. Insert Faculty
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Ravimaran', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'ravimaran-aid@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. P D Sheba Kezia Malarchelvi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'pdsheba-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. A Kavitha', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'kavitha7185@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. A Sridevi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'sridevi-aid@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. M Arunprakash', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'arunprakash7134@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. T Shanmuga Sundari', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'shanmugasundari7159@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Sadeesh', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'sadeesh7141@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms J Ambika', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'ambika7173@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr R Vetrivendan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'vetrivendan7177@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Ponnuthurai', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'ponnuthurai7122@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr P Dineshkumar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'dineshkumar7181@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. T Anita Dorothy', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'anitadorothy-aid@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. P Preethy Janet', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'preethyjanet7134@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. D Mangalambigai', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'mangalambigai7126@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. S Renganayaki', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.Sc.', 'Engineering & Technology Research', 'renganayaki7142@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. A Kayal', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'kayal-aid@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. G Nithyalakshmi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E. Assistant Professor nithyalakshmi-aid@saranathan.ac.in View profile', 'Engineering & Technology Research', 'nithyalakshmi-aid@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. C Gohila Priyadharshini', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'priyadharshini7130@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. A Pushpa', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'M.E.', 'Engineering & Technology Research', 'pushpa7140@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. A Belin Jude', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'CE'), 'M.Tech.', 'Engineering & Technology Research', 'belin-ce@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. K Sathya Prabha', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CE'), 'M.Tech.', 'Engineering & Technology Research', 'sathyaprabha-ce@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. A Anandraj', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CE'), 'M.Tech.', 'Engineering & Technology Research', 'anandraj-ce@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. B Sekar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CE'), 'M.E.', 'Engineering & Technology Research', 'sekar7132@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. C Kesava Raja', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CE'), 'M.E.', 'Engineering & Technology Research', 'kesavaraja-ce@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. G Venkatesan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CE'), 'M.Tech.', 'Engineering & Technology Research', 'venkatesan-ce@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Kannan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CE'), 'M.E.', 'Engineering & Technology Research', 'kannan7154@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Venkatasubramanian', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.E.', 'Engineering & Technology Research', 'veeyes@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. A Subasri', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.E.', 'Engineering & Technology Research', 'subasri7117@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. R Kannan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.E.', 'Engineering & Technology Research', 'kannan7137@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. K Vijayaragavan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.E.', 'Engineering & Technology Research', 'vijayaragavan7156@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Senthil', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.E.', 'Engineering & Technology Research', 'senthil7111@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. V Ranjani', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.E.', 'Engineering & Technology Research', 'ranjani-aiml@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms M Arunadevi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.E.', 'Engineering & Technology Research', 'arunadevi7171@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. A Abirami', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.E.', 'Engineering & Technology Research', 'abirami7123@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. A Thenmozhi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.E.', 'Engineering & Technology Research', 'thenmozhi-it@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. S Subiksha', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSBS'), 'M.Tech.', 'Engineering & Technology Research', 'subiksha7187@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSBS&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. V Punitha', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'punitha-it@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. R Senthamil Selvi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'senthamilselvi-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Mohana', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'mohana-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. K.S Chandrasekaran', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'chandrasekaran-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Rajalakshmi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'rajalakshmi7103@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. D Boobala Muralitharan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'boobala-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. R Sugantha Lakshmi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'lakshmi7127@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. T Nagalakshmi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'nagalakshmi7160@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. R Karthik', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'karthik-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. K Mohanappriya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'mohanapriya-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. J Sathiaparkavi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'parkavi-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. E Shapna Rani', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'shapnarani-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. P Rohini', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', '7133@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. C Maria Rhythm', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'mariarhythm7182@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. A Rachel Roselin', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'rachelroselin7158@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. N Ramya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'ramya-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. L Parthipan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'parthipan7129@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. G Sathya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.E.', 'Engineering & Technology Research', 'sathya7144@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. G Roshini', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'M.Tech.', 'Engineering & Technology Research', 'roshini7146@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. A Delphin Carolina Rani', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 'M.E.', 'Engineering & Technology Research', 'delphincarolinarani7163@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. B Rethina Kumar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 'M.E.', 'Engineering & Technology Research', 'rethinakumar-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. S Puvaneswari', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 'M.E.', 'Engineering & Technology Research', 'puvaneswari7125@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Amirthalingam', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 'M.E.', 'Engineering & Technology Research', 'amirthalingam7148@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. P Manikandan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 'M.E.', 'Engineering & Technology Research', 'manikandan7153@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. L Manimegalai', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 'M.E.', 'Engineering & Technology Research', 'manimegalai7178@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. S Srimathi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 'M.E.', 'Engineering & Technology Research', 'srimathi7168@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. P Kaviya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 'M.E. Assistant Professor kaviya-cse@saranathan.ac.in View profile', 'Engineering & Technology Research', 'kaviya-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. J J Arulsheela', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'AIML'), 'M.Tech.', 'Engineering & Technology Research', 'arulsheela7157@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=AIML&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Santhi', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'santhim@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. V Mohan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'mohan-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. P Shanmugapriya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.Tech.', 'Engineering & Technology Research', 'shanmugapriya-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Padmaa', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'padmaa-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. R Mukesh', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'mukesh7131@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S.A Arunmozhi', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.Tech.', 'Engineering & Technology Research', 'arunmozhi-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Rajeswari', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.Tech.', 'Engineering & Technology Research', 'rajeswaris-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Baritha Begum', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'barithabegum-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. K Malaisamy', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'malaisamy-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. G Sivakannu', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'sivakannu-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Kiruthiga', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'kiruthiga-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. N Preethi Elizabeth', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'preethielizabeth-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. B Divya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'divyab-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Hariprasath', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'hariprasath-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. P Sivagamasundhari', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'sivagamasundhari-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. J Eindhumathy', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'eindhumathy-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. M Mahendran', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.Tech.', 'Engineering & Technology Research', 'mahendran-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. M Anthuvan Lydia', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'M.E.', 'Engineering & Technology Research', 'anthuvanlydia-ece@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. C Krishnakumar', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.Tech.', 'Engineering & Technology Research', 'krishnakumar-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M.V Suganyadevi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.E.', 'Engineering & Technology Research', 'suganyadevi-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. D Kalyana Kumar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.Tech.', 'Engineering & Technology Research', 'kalyanakumar-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Marimuthu', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.E.', 'Engineering & Technology Research', 'marimuthu-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Ram Prasath', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.Tech.', 'Engineering & Technology Research', 'ramprasath-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. P Ram Prakash', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.E.', 'Engineering & Technology Research', 'ramprakash-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. R Vijay', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.Tech.', 'Engineering & Technology Research', 'vijay-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. N Gayathri', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.E.', 'Engineering & Technology Research', 'gayathri-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. C Pearline Kamalini', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.E.', 'Engineering & Technology Research', 'pearline-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. B Paranthagan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.E.', 'Engineering & Technology Research', 'paranthagan-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. R Balasubramanian', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.E.', 'Engineering & Technology Research', 'balasubramanian-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. P Rameshbabu', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.E.', 'Engineering & Technology Research', 'rameshbabu-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. R Sridhar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.Tech.', 'Engineering & Technology Research', 'sridhar-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Vigneshwaran', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'M.E.', 'Engineering & Technology Research', 'vigneshwarans-ice@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=EEE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Shanmugavalli', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'ICE'), 'M.Tech.', 'Engineering & Technology Research', 'shanmugavalli-ice@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ICE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. K Gaayathry', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'ICE'), 'M.E.', 'Engineering & Technology Research', 'gaayathry-ice@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ICE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. A Gopikrishnan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ICE'), 'M.E. Ph.D Assistant Professor gopi-ice@saranathan.ac.in View profile Mr. R Satheesh', 'Engineering & Technology Research', 'gopi-ice@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ICE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. R Satheesh', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ICE'), 'M.E.', 'Engineering & Technology Research', 'satheesh-eee@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ICE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. R Seetharaman', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ICE'), 'M.Tech.', 'Engineering & Technology Research', 'seetharaman-ice@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ICE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Prassanna Perumal', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ICE'), 'M.E.', 'Engineering & Technology Research', 'prassanna-ice@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ICE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. R Thillaikarasi', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.Tech.', 'Engineering & Technology Research', 'thillai-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. J Sangeethapriya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.Tech.', 'Engineering & Technology Research', 'jspriya-it@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. R Rengaraj alias Muralidharan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.E.', 'Engineering & Technology Research', 'rengaraj-it@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. V Senthil Balaji', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.E.', 'Engineering & Technology Research', 'senthilbalaji-it@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. A Sheelavathi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.E.', 'Engineering & Technology Research', 'sheelavathi-it@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. D Raghu Raman', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.E.', 'Engineering & Technology Research', 'raghuraman7188@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. K Muthukarupaee', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.E.', 'Engineering & Technology Research', 'muthukarupaee-it@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. M Jebarani', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.E.', 'Engineering & Technology Research', 'jebarani7104@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. G Sathiya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.E.', 'Engineering & Technology Research', 'sathiya-cse@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. S Angel Sweety Sheeba', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'IT'), 'M.E. Assistant Professor angel-it@saranathan.ac.in View profile', 'Engineering & Technology Research', 'angel-it@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=IT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. R Rekha', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.Tech.', 'Engineering & Technology Research', 'rekha-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. D VALAVAN', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.Tech.', 'Engineering & Technology Research', 'principal@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. N Baskar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E.', 'Engineering & Technology Research', 'baskar-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M R Anantha Padmanaban', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E.', 'Engineering & Technology Research', 'mrpadmanaban-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. G Mahesh', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.Tech.', 'Engineering & Technology Research', 'mahesh-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. A Mercy Vasan', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E.', 'Engineering & Technology Research', 'mercyvasan-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Ganesan', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E.', 'Engineering & Technology Research', 'ganesan-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Varatharajulu', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.Tech.', 'Engineering & Technology Research', 'varatharajulu7110@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Karthikeyan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E.', 'Engineering & Technology Research', 'karthikeyan-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. R Sureshbabu', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.Tech.', 'Engineering & Technology Research', 'sureshbabu-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. P Sathis Kumar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E.', 'Engineering & Technology Research', 'sathiskumar7112@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. A Ravindran', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E. Assistant Professor ravindran7099@saranathan.ac.in View profile', 'Engineering & Technology Research', 'ravindran7099@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. P V Rajesh', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E.', 'Engineering & Technology Research', 'rajesh-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Vinoth Kumar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.Tech.', 'Engineering & Technology Research', 'vinothkumar-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. P Vigneshwar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E.', 'Engineering & Technology Research', 'vigneshwar-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. K Amarnath', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MECH'), 'M.E.', 'Engineering & Technology Research', 'amar-mech@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MECH&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. K Karthikeyan', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'MBA'), 'B.E.', 'Engineering & Technology Research', 'karthikeyan-mba@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MBA&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. V Mahalakshmi', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MBA'), 'M.E.', 'Engineering & Technology Research', 'mahalakshmi-mba@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MBA&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Saravanan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MBA'), 'B.E.', 'Engineering & Technology Research', 'saravanan-mba@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MBA&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. S Syed Muthaliff', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MBA'), 'M.Phil.', 'Engineering & Technology Research', 'syed-mba@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MBA&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. C R Surekha', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MBA'), 'M.E.', 'Engineering & Technology Research', 'surekha7139@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MBA&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. M Ashwin', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MBA'), 'B.E.', 'Engineering & Technology Research', 'ashwin7162@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MBA&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. L Muruganandam', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'CHE'), 'M.Sc.', 'Engineering & Technology Research', 'muruganandam-che@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CHE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. V Balamurugan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CHE'), 'M.Sc.', 'Engineering & Technology Research', 'balamurugan-che@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CHE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. G Thulasi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CHE'), 'M.Sc.', 'Engineering & Technology Research', 'thulasi-che@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CHE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Priyarega', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CHE'), 'M.Sc.', 'Engineering & Technology Research', 'priyarega-che@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CHE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. A Lakshmanan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'CHE'), 'M.Sc.', 'Engineering & Technology Research', 'lakshmanan-che@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=CHE&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Bhuvaneswari', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'ENG'), 'M.Phil.', 'Engineering & Technology Research', 'bhuvaneswari-eng@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ENG&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. A Lakshmi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ENG'), 'M.Phil.', 'Engineering & Technology Research', 'lakshmi-eng@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ENG&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. G Sriram', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ENG'), 'M.Phil.', 'Engineering & Technology Research', 'sriram-eng@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ENG&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. G Vijayarenganayaki', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ENG'), 'M.E.', 'Engineering & Technology Research', 'vijayarenganayaki7164@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ENG&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. C Gnanadesikan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'ENG'), 'M.Phil.', 'Engineering & Technology Research', 'gnanadesikan-eng@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=ENG&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. R Neelambari', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'neelambari-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. G Ravichandran', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'ravichandran-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. D Geetha', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'geetha-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Anupriya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'anu-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Sivamani', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'sivamani-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Revathi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'revathi-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Arunkumar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'arunkumar-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. P.K Lakshmidevi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'lakshmidevi-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. T Prabha', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'prabha-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. N Subashini', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'subhashini-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. R Buvaneswari', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'buvaneswari-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. S Dinesh', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'MAT'), 'M.Sc.', 'Engineering & Technology Research', 'dinesh-mat@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=MAT&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. R Mariappan', 'Professor & Head', (SELECT dept_id FROM departments WHERE dept_code = 'PHY'), 'M.Sc.', 'Engineering & Technology Research', 'mariappan-phy@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=PHY&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. P Senthilkumar', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'PHY'), 'M.Sc.', 'Engineering & Technology Research', 'senthilkumar-phy@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=PHY&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Murali', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'PHY'), 'M.Sc.', 'Engineering & Technology Research', 'murali-phy@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=PHY&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Nidya', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'PHY'), 'M.Sc.', 'Engineering & Technology Research', 'nidya-phy@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=PHY&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Mr. G Anantha Krishnan', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'PHY'), 'M.Sc.', 'Engineering & Technology Research', 'ananthakrishnan-phy@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=PHY&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Ms. P Saravana Devi', 'Assistant Professor', (SELECT dept_id FROM departments WHERE dept_code = 'PHY'), 'M.Sc.', 'Engineering & Technology Research', 'saravanadevi-phy@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=PHY&tgt=faculty');
INSERT INTO faculty (faculty_name, designation, dept_id, qualification, research_area, email, phone, source_url) VALUES ('Dr. M Thangam', 'Associate Professor', (SELECT dept_id FROM departments WHERE dept_code = 'TAM'), 'M.Phil.', 'Engineering & Technology Research', 'thangam7092@saranathan.ac.in', '0431-2473684', 'http://saranathan.ac.in/dept.php?dept=TAM&tgt=faculty');

-- 4. Insert Academic Calendar
INSERT INTO academic_calendar (academic_year, semester, event_name, event_date, description, source_url) VALUES ('2026-2027', 'Odd Semester', 'Commencement of Classes for Higher Semesters', '2026-07-15', 'Reopening date for 3rd, 5th, and 7th semester students.', 'http://saranathan.ac.in/');
INSERT INTO academic_calendar (academic_year, semester, event_name, event_date, description, source_url) VALUES ('2026-2027', 'Odd Semester', 'First Assessment Test (IAT-1)', '2026-08-20', 'First internal continuous assessment exam for all departments.', 'http://saranathan.ac.in/');
INSERT INTO academic_calendar (academic_year, semester, event_name, event_date, description, source_url) VALUES ('2026-2027', 'Odd Semester', 'Second Assessment Test (IAT-2)', '2026-10-05', 'Second internal continuous assessment exam.', 'http://saranathan.ac.in/');
INSERT INTO academic_calendar (academic_year, semester, event_name, event_date, description, source_url) VALUES ('2026-2027', 'Odd Semester', 'End Semester Autonomous Practical Examinations', '2026-11-10', 'Lab examinations conducted by Controller of Examinations.', 'http://saranathan.ac.in/');

-- 5. Insert Examination Notices
INSERT INTO exam_notices (notice_title, notice_date, semester, description, pdf_link, source_url) VALUES ('Autonomous End-Semester Examination Time Table Nov 2026', '2026-07-10', 'Odd Semester', 'Official schedule for Autonomous End-Semester Theory Examinations.', 'http://saranathan.ac.in/coe/index.php', 'http://saranathan.ac.in/coe/index.php');
INSERT INTO exam_notices (notice_title, notice_date, semester, description, pdf_link, source_url) VALUES ('Revaluation Application Procedure 2026', '2026-06-15', 'Even Semester', 'Guidelines and fee structure for answer script revaluation.', 'http://saranathan.ac.in/coe/index.php', 'http://saranathan.ac.in/coe/index.php');

-- 6. Insert Timetables
INSERT INTO timetables (dept_id, semester, academic_year, pdf_url, last_updated, source_url) VALUES ((SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'Odd Semester 2026', '2026-2027', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=cseabout', '2026-07-01', 'http://saranathan.ac.in/dept.php?dept=CSE&tgt=cseabout');
INSERT INTO timetables (dept_id, semester, academic_year, pdf_url, last_updated, source_url) VALUES ((SELECT dept_id FROM departments WHERE dept_code = 'AIDS'), 'Odd Semester 2026', '2026-2027', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=aids_about', '2026-07-01', 'http://saranathan.ac.in/dept.php?dept=AIDS&tgt=aids_about');
INSERT INTO timetables (dept_id, semester, academic_year, pdf_url, last_updated, source_url) VALUES ((SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'Odd Semester 2026', '2026-2027', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=eceabt', '2026-07-01', 'http://saranathan.ac.in/dept.php?dept=ECE&tgt=eceabt');

-- 7. Insert Announcements
INSERT INTO announcements (title, category, publish_date, description, attachment_url, source_url) VALUES ('Instructions for TNEA 2026 allotted students', 'General Notice', '2026-07-01', 'Official Notification: Instructions for TNEA 2026 allotted students', 'https://drive.google.com/file/d/1-UF9X7i7gwUuflp_NsL4d7RKLGLR-yl8/view?usp=sharing', 'http://saranathan.ac.in/');
INSERT INTO announcements (title, category, publish_date, description, attachment_url, source_url) VALUES ('MBA,  M.E., Data Sheet (2026-2027) Admissions (Management Quota)', 'General Notice', '2026-07-01', 'Official Notification: MBA,  M.E., Data Sheet (2026-2027) Admissions (Management Quota)', 'https://forms.gle/ygLcjjuxvLNGertBA', 'http://saranathan.ac.in/');
INSERT INTO announcements (title, category, publish_date, description, attachment_url, source_url) VALUES ('LATERAL ENTRY - DIRECT II Year B.E./B.Tech. Admissions 2026-27(Datasheet)', 'General Notice', '2026-07-01', 'Official Notification: LATERAL ENTRY - DIRECT II Year B.E./B.Tech. Admissions 2026-27(Datasheet)', 'https://forms.gle/FquboEAsbYHWQaz18', 'http://saranathan.ac.in/');

-- 8. Insert Placement Drives
INSERT INTO placement_drives (company_name, drive_date, eligibility, package_offered, registration_link, status, source_url) VALUES ('Zoho Corporation', '2026-02-15', 'B.E / B.Tech / MBA All Streams', '5.5 - 8.5 LPA', 'https://drive.google.com/file/d/1HaElo8IszvZS6jhA-MUP-Y19HmxLcCbR/view', 'Completed', 'http://saranathan.ac.in/');
INSERT INTO placement_drives (company_name, drive_date, eligibility, package_offered, registration_link, status, source_url) VALUES ('Delphi TVS Technologies', '2026-01-20', 'B.E. EEE / MECH / ECE', '4.0 - 5.0 LPA', 'https://drive.google.com/file/d/16g9dMjxFx4RmEs9jghtushlhQ_tJqyrq/view', 'Completed', 'http://saranathan.ac.in/');
INSERT INTO placement_drives (company_name, drive_date, eligibility, package_offered, registration_link, status, source_url) VALUES ('Mallow Technologies', '2026-01-10', 'B.E CSE / IT / AIDS', '4.5 LPA', 'https://drive.google.com/file/d/1RqEv07fVAfzXQOeSjvlkKeCrrw2XOYNH/view', 'Completed', 'http://saranathan.ac.in/');
INSERT INTO placement_drives (company_name, drive_date, eligibility, package_offered, registration_link, status, source_url) VALUES ('IBM Development Initiative', '2025-12-05', 'All Pre-Final & Final Year Students', '6.0 LPA', 'https://drive.google.com/file/d/1CIYVxbvTKaJflPAblqxa3ty3mHS1z8x6/view', 'Completed', 'http://saranathan.ac.in/');
INSERT INTO placement_drives (company_name, drive_date, eligibility, package_offered, registration_link, status, source_url) VALUES ('SpringFive Consulting', '2025-11-18', 'B.E / B.Tech Graduates', '5.0 LPA', 'https://drive.google.com/file/d/1qNdIhlQ43yWpAmpbSP3c1tnWVvN89uB5/view', 'Completed', 'http://saranathan.ac.in/');
INSERT INTO placement_drives (company_name, drive_date, eligibility, package_offered, registration_link, status, source_url) VALUES ('MM Forgings', '2025-10-25', 'B.E. Mechanical & Civil', '3.8 LPA', 'https://drive.google.com/file/d/1sZjEjUD9NgRePJkVVWrLouqta9nbba3C/view', 'Completed', 'http://saranathan.ac.in/');

-- 9. Insert Clubs & Cells
INSERT INTO clubs (club_name, category, faculty_coordinator, description, activities, contact_email, source_url) VALUES ('Entrepreneurship Development Cell (EDC)', 'Innovation & Entrepreneurship', 'Dr. S. M. Girirajkumar', 'Fosters entrepreneurial spirit and startup incubation among engineering students.', 'Bootcamps, Pitching sessions, E-Summit', 'edc@saranathan.ac.in', 'http://saranathan.ac.in/center.php?tgt=edcell');
INSERT INTO clubs (club_name, category, faculty_coordinator, description, activities, contact_email, source_url) VALUES ('E-Yantra Robotics Club', 'Robotics & Embedded Systems', 'Dr. C. Krishnakumar', 'IIT Bombay backed initiative to train students in real-world Embedded Systems and Robotics.', 'Robotics competitions, Hardware hackathons', 'eyantra@saranathan.ac.in', 'http://saranathan.ac.in/center.php?tgt=eyantra_abt');
INSERT INTO clubs (club_name, category, faculty_coordinator, description, activities, contact_email, source_url) VALUES ('Women Empowerment Cell (WEC)', 'Social & Equity', 'Dr. V. Punitha', 'Dedicated cell empowering female students and staff through leadership workshops.', 'Women''s Day Celebrations, Self-defense training', 'wec@saranathan.ac.in', 'http://saranathan.ac.in/center.php?tgt=wecell');
INSERT INTO clubs (club_name, category, faculty_coordinator, description, activities, contact_email, source_url) VALUES ('National Service Scheme (NSS)', 'Community Service', 'NSS Programme Officer', 'Engages students in social service and rural development programs.', 'Blood donation camps, Tree plantation, Village adoption', 'nss@saranathan.ac.in', 'http://saranathan.ac.in/commonfaci.php?tgt=nssevent');
INSERT INTO clubs (club_name, category, faculty_coordinator, description, activities, contact_email, source_url) VALUES ('Youth Red Cross (YRC)', 'Health & Humanitarian', 'YRC Officer', 'Promotes health awareness and emergency relief response capabilities.', 'First aid training, Health checkup camps', 'yrc@saranathan.ac.in', 'http://saranathan.ac.in/commonfaci.php?tgt=yrcevent');

-- 10. Insert Research Centres
INSERT INTO research_centres (centre_name, dept_id, coordinator, description, source_url) VALUES ('Saranathan Center for Engineering Research (SCERC)', (SELECT dept_id FROM departments WHERE dept_code = 'CSE'), 'Dean (Research)', 'Central R&D facility coordinating PhD scholars and sponsored research projects.', 'http://saranathan.ac.in/center.php?tgt=scerc');
INSERT INTO research_centres (centre_name, dept_id, coordinator, description, source_url) VALUES ('Institute Industry Partnership Cell (IIPC)', (SELECT dept_id FROM departments WHERE dept_code = 'EEE'), 'Dr. C. Krishnakumar', 'Facilitates industrial consultancy and collaborative research with power sector companies.', 'http://saranathan.ac.in/center.php?tgt=eeeiipc');
INSERT INTO research_centres (centre_name, dept_id, coordinator, description, source_url) VALUES ('Quality Improvement Cell (QIC)', (SELECT dept_id FROM departments WHERE dept_code = 'ECE'), 'Head QIC', 'Drives faculty research quality and pedagogy enhancement.', 'http://saranathan.ac.in/center.php?tgt=qicell');

-- 11. Insert Gallery Images
INSERT INTO gallery (image_title, event_name, category, image_url, source_url) VALUES ('Silver Jubilee Auditorium Inauguration', 'Silver Jubilee Celebration', 'Campus Event', 'http://saranathan.ac.in/galleryalbum.php', 'http://saranathan.ac.in/galleryalbum.php');
INSERT INTO gallery (image_title, event_name, category, image_url, source_url) VALUES ('Smart India Hackathon Winners', 'SIH Hackathon 2025', 'Student Achievements', 'http://saranathan.ac.in/galleryalbum.php', 'http://saranathan.ac.in/galleryalbum.php');

-- 12. Insert Campus Buildings
INSERT INTO campus_buildings (building_name, building_type, description, location, source_url) VALUES ('Main Academic Block', 'Academic & Administrative', 'Houses Administrative Office, Principal Office, CSG Labs, and Department Classrooms.', 'Central Campus', 'http://saranathan.ac.in/');
INSERT INTO campus_buildings (building_name, building_type, description, location, source_url) VALUES ('Silver Jubilee Auditorium', 'Auditorium', 'State-of-the-art air-conditioned auditorium for international conferences and college fests.', 'North Campus', 'http://saranathan.ac.in/');
INSERT INTO campus_buildings (building_name, building_type, description, location, source_url) VALUES ('Central Library Building', 'Library', 'Multi-story library with digital resources, IEEE subscriptions, and study halls.', 'Academic Block 2', 'http://saranathan.ac.in/commonfaci.php?tgt=libabout');
INSERT INTO campus_buildings (building_name, building_type, description, location, source_url) VALUES ('Student Hostels (Boys & Girls)', 'Residential', 'Separate residential blocks with modern mess facilities and Wi-Fi connectivity.', 'South Campus', 'http://saranathan.ac.in/commonfaci.php?tgt=hostel');

-- 13. Insert Contact Information
INSERT INTO contact_information (office_name, address, phone, email, website, source_url) VALUES ('Saranathan College of Engineering - Main Office', 'Venkateswara Nagar, Trichy-Madurai Main Road, NH 45B, Panjappur, Tiruchirappalli, Tamil Nadu 620012', '0431-2473684 / 2473685', 'principal@saranathan.ac.in', 'https://www.saranathan.ac.in', 'http://saranathan.ac.in/contactus.php');
INSERT INTO contact_information (office_name, address, phone, email, website, source_url) VALUES ('Placement Cell', 'Training & Placement Block, Saranathan College of Engineering, Trichy', '0431-2473684 Ext: 104', 'placement@saranathan.ac.in', 'https://www.saranathan.ac.in', 'http://saranathan.ac.in/placement.php?tgt=placontact');
